# Mathematical Pointwise PyTorch Operations

An short introduction about PyTorch and about the chosen functions.

PyTorch is an open source machine learning library used for computer vision and natural language processing.

Pointwise Operations work with single value calculations. Following are the five functions:

- acos
- add
- ceil
- floor
- mul

Before we begin, let's install and import PyTorch

In [18]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [19]:
# Import torch and other required modules
import torch

## Function 1 - torch.acos 

Computes the inverser cosine of each element of the input.

In [20]:
# Example 1 - working 
t=torch.rand(4)
print(t)
final=torch.acos(t)
print(final)

tensor([0.4116, 0.2181, 0.7697, 0.6162])
tensor([1.1465, 1.3510, 0.6924, 0.9069])


torch.rand(n) generates the n random numbers of the range between 0 to 1.
The result is stored in t variable.

torch.acos(t) is applied for inverse cosine of the random numbers generated and the result is stored in final variable.

In [21]:
# Example 2 - working
t=torch.tensor([-0.3133,-0.222])
print(t)
final=torch.acos(t)
print(final)

tensor([-0.3133, -0.2220])
tensor([1.8895, 1.7947])


torch.tensor() has 2 values to be processed for inverse cosine which is stored in t variable.
Finally, final variable stores the result of torch.acos(t).

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
t=torch.tensor([5,-6.2],[2.])
print(t)
final=torch.acos(t)
print(final)

TypeError: ignored

torch.tensor() must have the identical shape of values.
Here, in the first row, there are 2 elements, but in the second row only one element is present, so TypeError is thrown with 1 positional argument.

It must be something like: torch.tensor([[5,-6.2],[2.,3]]).

torch.acos() function can be used when there is a need of inverse cosine in trignometric operations.

Let's save our work using Jovian before continuing.

In [23]:
!pip install jovian --upgrade --quiet

In [24]:
import jovian

In [25]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/sagarp3199/01-tensor-operations


'https://jovian.ai/sagarp3199/01-tensor-operations'

## Function 2 - torch.add

Adds the scalar value to the input resulting in new tensor.

In [27]:
# Example 1 - working
a=torch.rand(5)
print(a)
final=torch.add(a,40)
print(final)

tensor([0.1586, 0.6890, 0.4911, 0.8014, 0.8743])
tensor([40.1586, 40.6890, 40.4911, 40.8014, 40.8743])


torch.rand(n) generates the n random numbers of the range between 0 to 1.
The result is stored in a variable.

torch.add(a,40) adds 40 value to each element of tensor a resulting in final tensor variable.

In [30]:
# Example 2 - working
a=torch.randn(5)
print(a)
b=torch.randn(5,1)
print(b)
final=torch.add(a,b,alpha=10)
print(final)

tensor([-0.4378, -1.4105, -0.3065, -1.0976,  0.5638])
tensor([[-0.1570],
        [-0.0868],
        [ 2.1155],
        [ 0.4016],
        [-0.7831]])
tensor([[-2.0079, -2.9806, -1.8767, -2.6677, -1.0063],
        [-1.3056, -2.2783, -1.1743, -1.9654, -0.3040],
        [20.7177, 19.7449, 20.8489, 20.0578, 21.7192],
        [ 3.5779,  2.6052,  3.7091,  2.9181,  4.5794],
        [-8.2691, -9.2419, -8.1379, -8.9290, -7.2676]])


Two tensors 'a' and 'b' are created using torch.randn() function.
'a' is 1x5 matrix and 'b' is 5x1 matrix

torch.add(a,b,alpha=n) results in a + b*n
Here, alpha is 10 and it is added to the random values in b and then result is added to a vector. The final solution is stored in final tensor variable.

In [38]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.randn(3)
print(a)
b=torch.randn(2,3)
print(b)
final=torch.add(a,1/0,alpha=10)
print(final)

tensor([-0.5190, -2.0658,  0.3427])
tensor([[-0.6351, -1.5383,  1.4964],
        [ 0.2821,  0.2843,  0.3729]])


ZeroDivisionError: ignored

The error is in the torch.add() function where 2nd parameter is 1/0 which is infinity which can't be added to a function resulting in ZeroDivisionError.

It can be written : final=torch.add(a,b,alpha=10)

The torch.add() function is used when some scalar value is needed to add into some tensor to maximise the value.

In [39]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/sagarp3199/01-tensor-operations


'https://jovian.ai/sagarp3199/01-tensor-operations'

## Function 3 - torch.ceil

Returns a new tensor with the ceil of the elements of input which means the smallest integer greater than or equal to the each element.

In [40]:
# Example 1 - working
a=torch.randn(5)
print(a)
final=torch.ceil(a)
print(final)

tensor([ 0.5238, -0.2964,  0.3027,  1.3336, -0.8395])
tensor([1., -0., 1., 2., -0.])


torch.rand(n) generates the n random numbers and the result is stored in 'a' variable.

torch.ceil(a) function returns the tensor of the integer values with integers greater than or equal to the value.

In [41]:
# Example 2 - working
a=torch.tensor([-3.223,-1.22,4.33,5.32])
print(a)
final=torch.ceil(a)
print(final)

tensor([-3.2230, -1.2200,  4.3300,  5.3200])
tensor([-3., -1.,  5.,  6.])


torch.tensor() has four integers with any values which are stored in 'a' variable.
torch.ceil(a) function returns the tensor of the integer values with integers greater than or equal to the value.

In [43]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.tensor([3.4,-2,[2],4.22])
print(a)
final=torch.ceil(a)
print(final)

TypeError: ignored

torch.tensor must contain the real number inside it. Here, the list is stored, so TypeError comes.
It must be like: a=torch.tensor([3.4,-2,2,4.22])

torch.ceil() is used when the nearest maximum integer is needed to find from the tensor.

In [44]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/sagarp3199/01-tensor-operations


'https://jovian.ai/sagarp3199/01-tensor-operations'

## Function 4 - torch.floor

Returns a new tensor with the floor of the elements of input, the largest integer less than or equal to each element.

In [48]:
# Example 1 - working
a=torch.randn(8)
print(a)
final=torch.floor(a)
print(final)

tensor([-0.5695,  1.1187,  1.7829,  0.7669, -0.2075, -1.7565,  0.4958, -0.3051])
tensor([-1.,  1.,  1.,  0., -1., -2.,  0., -1.])


torch.rand(n) generates the n random numbers and the result is stored in 'a' variable.

torch.floor(a) function returns the tensor of the integer values with integers less than or equal to the value.

In [50]:
# Example 2 - working
a=torch.tensor([4.2332,-3.4,33.119,-4.99])
print(a)
final=torch.floor(a)
print(final)

tensor([ 4.2332, -3.4000, 33.1190, -4.9900])
tensor([ 4., -4., 33., -5.])


torch.tensor() has four integers with any values which are stored in 'a' variable.
torch.floor(a) function returns the tensor of the integer values with integers less than or equal to the value.

In [51]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.tensor([],[3,4],[33])
print(a)
final=torch.floor(a)
print(final)

TypeError: ignored

torch.tensor() must have similar size matrices for operations. Here, empty variable and values of different size are mentioned so there is error of Type.
It must be like: a=torch.tensor([3,3,4,33])

torch.floor() is used when the smallest and nearest integer is needed in the tensor operations.

In [52]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/sagarp3199/01-tensor-operations


'https://jovian.ai/sagarp3199/01-tensor-operations'

## Function 5 - torch.mul

Multiplies each element of the input input with the scalar other and returns a new resulting tensor.

In [53]:
# Example 1 - working
a=torch.randn(5)
print(a)
final=torch.mul(a,100)
print(final)

tensor([ 1.2423, -0.1203, -0.1017, -1.9997, -0.1825])
tensor([ 124.2269,  -12.0281,  -10.1679, -199.9730,  -18.2535])


torch.randn() functions generates random numbers and stored in 'a' variable.
torch.mul() receives 2 arguments with index 100 to be multiplied to each element resulting in final tensor variable.

In [54]:
# Example 2 - working
a=torch.tensor([3.44,2])
print(a)
final=torch.mul(a,0.1)
print(final)

tensor([3.4400, 2.0000])
tensor([0.3440, 0.2000])


torch.mul() function multiplies 'a' value to 0.1 value resulting in final variable.


In [55]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.tensor([3.44,2],[2])
print(a)
final=torch.mul(a,0.1)
print(final)

TypeError: ignored

TypeError comes due to the unmatched size of matrix to be load in torch.tensor() function.

torch.mul() is used when scalar is needed to multiply and increase the value of tensor variables.

In [56]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/sagarp3199/01-tensor-operations


'https://jovian.ai/sagarp3199/01-tensor-operations'

## Conclusion

Covered five basic mathematical functions used in tensor library namely acos, add, ceil, floor and mul.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [57]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/sagarp3199/01-tensor-operations


'https://jovian.ai/sagarp3199/01-tensor-operations'